language: rust
os:
  - osx
  - linux
install:
  - sudo python -m pip install Mako
addons:
  apt:
    packages:
    - libva-dev
rust:
  - nightly
notifications:
  webhooks: http://build.servo.org:54856/travis
